
// This file is generated by Firebase Genkit.
import { initializeApp, getApp, getApps } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';

const firebaseConfig = {
  projectId: 'dataneuron-digital',
  appId: '1:5877870390:web:f4830d57980046233f8d97',
  storageBucket: 'dataneuron-digital.firebasestorage.app',
  apiKey: 'AIzaSyAfJ6NnYS4g5Yk2Bbd-NKXsOf4aP4KDBfQ',
  authDomain: 'dataneuron-digital.firebaseapp.com',
  messagingSenderId: '5877870390',
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);
const storage = getStorage(app);

export { app, db, storage };
